
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>



int patternMatching(int sizeText, int sizePattern, char * text, char * pattern){
    int index = 0;
    int totalPatternFound = 0;
    for (int i = 0; i <= sizeText - sizePattern; i++)
    {
        bool patternFound = true;
        for (int j = 0; j < sizePattern; j++)
        {
            if (text[i+j] != pattern[j]){
                patternFound = false;
                break;
            }
        }
        if(patternFound){
            printf("Pattern found at index %d \n",i);
            index ++;
            totalPatternFound ++;
        }
    }
    //printf("We found %d times the pattern %s in the text %s",totalPatternFound,pattern,text);


    return totalPatternFound;
    
}


int main(int argc, char const *argv[])
{   
    //text and pattern generated by GPT
    char * text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur";
    int sizeText = strlen(text);
    char * pattern = "dolor";
    int sizePattern = strlen(pattern);

    int total = patternMatching(sizeText,sizePattern,text,pattern);

    printf("Pattern found %d times \n",total);

    return 0;
}
